name: Build Debian Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian_version: [bullseye, bookworm]
    
    steps:
    - name: Checkout packaging repository
      uses: actions/checkout@v4
      with:
        path: packaging
    
    - name: Clone ustreamer repository
      run: |
        git clone --depth 1 --branch v6.40 https://github.com/pikvm/ustreamer.git ustreamer
    
    - name: Copy debian folder to ustreamer
      run: |
        cp -r packaging/debian ustreamer/
    
    - name: Create output directory
      run: |
        mkdir -p output
    
    - name: Build Debian package in Docker
      run: |
        docker run --rm \
          -v $(pwd)/ustreamer:/src \
          -v $(pwd)/output:/output \
          -w /src \
          debian:${{ matrix.debian_version }} \
          bash -c "
            apt-get update && \
            DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
              debhelper \
              libevent-dev \
              libjpeg62-turbo-dev \
              libbsd-dev \
              libgpiod-dev \
              libsystemd-dev \
              pkg-config \
              gcc \
              make \
              dpkg-dev \
              fakeroot \
              build-essential && \
            dpkg-buildpackage -us -uc -b && \
            mv ../*.deb /output/ || true && \
            mv ../*.buildinfo /output/ || true && \
            mv ../*.changes /output/ || true
          "
    
    - name: List generated packages
      run: |
        ls -lh output/
    
    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: ustreamer-debian-${{ matrix.debian_version }}
        path: "output/*.deb"
        if-no-files-found: error
